### ISSUE TITLE
cv or personal website?

### ISSUE THREAD

**Issue by bradreeder** [Jwhiles/john-whiles-dot-com#27]
Having a lot of text is fine if you intend the site as your personal website. If you intend to share it with employers as your cv bare in mind many don't look at a cv for more than ten seconds and won't read it all. They just want to quickly distill x applications down to a short-list for interview, so it's best to structure it so someone can glean the core information they need quickly.

In terms of content, only line I'd consider rephrasing:

"I love learning and only really feel comfortable when I've developed a deep understanding of the technologies that I employ."

I understand you mean that you strive to have a deep understanding of the technologies you use, but bare in mind you'll be in environments where you will have to learn and implement new things on the go as you're understanding it. Your project work here has prepared you for that, so there's no need to come across as uncomfortable in using things you're unfamiliar with.

**Comment by Jwhiles** [comment]
Thanks @bradreeder . 
I was intending this to act as an online CV with a tech blog, for the duration of my job hunt, and thereafter morph into John's internet house. Maybe trying to server dual purposes in this way is unwise. It's also been a big learning/reinforcement exercise


I totally understand what you mean about that sentence. I've revised to
```
A full stack web developer based in London. I love learning and building a deep understanding of the technologies I use. Examples of my work accross the tech stack can be found on my Github page.
```
I think this makes my idea a bit clearer? The content is a bit more concise, and project focused.
