### ISSUE TITLE
Add some form of github markdown interpreter for blog posts

### ISSUE THREAD

**Issue by Jwhiles** [Jwhiles/john-whiles-dot-com#3]
There must be modules to do this? I will look into it.

**Comment by nelsonic** [comment]
@Jwhiles this might help: https://github.com/dwyl/ampl

**Comment by Jwhiles** [comment]
@nelsonic  I want to use markdown primarily to style blog posts, and with my current marked set up unless I style my headers with lots of hashes eg `### blog title` - it's messing up the semantic structure of the page.. 

I'm finding marked a bit fiddly to achieve what I want, so I'll have a look at ampl as well :)

**Comment by nelsonic** [comment]
Sounds good. ✅ 
you've made some _impressive_ progress on this! 😍 
Hope you're having a great weekend. 👍
